"""
Django settings for django_insecure_project project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ========================
# Security mode toggle
# ========================
# Activate with: set DJANGO_SECURE=true  (on Windows PowerShell)
DJANGO_SECURE = os.getenv("DJANGO_SECURE", "false").lower() == "true"

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=lp9ay(_x@#c!&$xs$!1kbpu+kolydd3z%x918zm+@n7^d)a%m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not DJANGO_SECURE

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# ========================
# Application definition
# ========================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'csp',
]

MIDDLEWARE = [
    'csp.middleware.CSPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_insecure_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_insecure_project.wsgi.application'

# ========================
# Database
# ========================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ========================
# Password validation
# ========================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ========================
# Internationalization
# ========================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ========================
# Static files
# ========================
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# ========================
# Default primary key field type
# ========================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========================
# Cookie Security
# ========================
SESSION_COOKIE_SECURE = DJANGO_SECURE        # Only send session cookies over HTTPS
CSRF_COOKIE_SECURE = DJANGO_SECURE           # Only send CSRF cookies over HTTPS

SESSION_COOKIE_HTTPONLY = True               # JS cannot access session cookie
CSRF_COOKIE_HTTPONLY = False                 # Must remain False for CSRF token to work

SESSION_COOKIE_SAMESITE = "Lax"              # Helps prevent CSRF
CSRF_COOKIE_SAMESITE = "Lax"



SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False



# Étape 7: Security Headers

# Protection contre le MIME sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True  

# Contrôle du header Referer
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"  

# Protection contre le clickjacking
X_FRAME_OPTIONS = "DENY"  



CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),
        "script-src": ("'self'",),
        "style-src": ("'self'",),
    }
}
